export const pwdEncryptPublicKey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDJewkB6e4XuEyc9W7Oc3gfLBqh
IgRhTeH7+LByWMtLZvjHkBedAyHFBwO+ZueO+ejunEG0tS/0RhiM7GXyyNo1svQG
lRKCrYsGq9MDyWQQufVwU20Xx77GUe8Wxs27AbOe4Bv8cGSdC4atmsZhFHL+Fi/v
odbHJ1dMFaiSiyA4cQIDAQAB
-----END PUBLIC KEY-----`;
